

//== Meta Component ============================================================

/*-- Documentation -------------------------------

  The Meta component is automatically included in every page generated by Next.
  This component should include standard html boilerplate, such as the charSet.
  It should also include any libraries or linked stylesheets required globally.
  It does not accept any props.

*/

//-- Dependencies --------------------------------
import Head from 'next/head';

//-- React Implementation ------------------------
const Meta = () => (
  <Head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charSet="utf-8" />
    <link href='https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.0.3/leaflet.css' rel='stylesheet'></link>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css"></link>
    <script src="//widget.cloudinary.com/global/all.js" type="text/javascript"></script>
    <title>Backpaca</title>
  </Head>
);
export default Meta;
